version: "3.9"
services:
  postgres:
    image: postgres:13
    container_name: postgres
    networks:
      - vou-network
    env_file:
      - apps/main-api/.env
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-vou
    networks:
      - vou-network
    env_file:
      - apps/main-api/.env
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  redis:
    image: redis:6
    container_name: redis
    networks:
      - vou-network
    env_file:
      - apps/main-api/.env
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  account-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: account-service
        STAGE: dev
        NODE_MODULE_PATH: ./node_modules
        IS_RUN_MIGRATION: true
    ports:
      - "3001:3001"
    env_file:
      - ./apps/account-service/.env.build
    container_name: account-service
    depends_on:
      - postgres
    networks:
      - vou-network

  main-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: main-api
        STAGE: dev
        NODE_MODULE_PATH: ./node_modules
        IS_RUN_MIGRATION: false
    ports:
      - "3000:3000"
    container_name: main-api
    depends_on:
      - postgres
    networks:
      - vou-network

volumes:
  postgres-data:
  rabbitmq-data:
  redis-data:

networks:
  vou-network:
    driver: bridge
