FROM nginx:alpine

COPY ./vou.social.conf /etc/nginx/sites-available/vou.social.conf

RUN ln -s /etc/nginx/sites-available/vou.social.conf /etc/nginx/sites-enabled/

# Install certbot
RUN apk add --no-cache certbot certbot-nginx

# Generate SSL certificate
RUN certbot --nginx --non-interactive --agree-tos --register-unsafely-without-email -d vou.social -d www.vou.social